# Generated by Django 5.1.7 on 2025-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_code',
            field=models.CharField(default='000', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
