# Generated by Django 5.1.7 on 2025-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_city_code_city_description_city_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
